### ISSUE TITLE
Tool Not Working

### ISSUE THREAD

**Issue by MaiadaMahmoud** [reverse-unina/AndroidRipper#9]
I've tried running the tool, the AndroidRipper doesn't give me any output so I'm not sure if it's working correctly or not, the folders "model", "coverage" and "junit" are empty.

I've also tried continuing to the XML2jUnitForAndroidRipper but it gives an error when I run the batch file.  error: Model dir not found!

I've tried running the tool on Mac OS and on Windows 7

Your help would be much appreciated

**Comment by nicola-amatucci** [comment]
Please look at this [wiki page](https://github.com/reverse-unina/AndroidRipper/wiki/First-AndroidRipper-Execution).

Does your system comply with the requirements within the Prerequisites section?

**Comment by MaiadaMahmoud** [comment]
Thank you for the quick reply

Yes I went through all of the requirements and I'm also creating a new AVD for each couple of trials. The installer finishes with only one error at the "adb shell rm" command, it outputs a path with double slashes " // " so the error is that the file to be removed doesn't exist. I don't know how to fix this problem

When I move forward with the Driver it starts the AVD and finishes completely but I don't know how to get the model and the coverage.. the folder of the coverage is empty and the model folder has one file called "activities.xml" but it is empty as well.

I'll try to uninstall everything and start over again but is there something else that I should do?

**Comment by nicola-amatucci** [comment]
Is the app developed with Eclipse ADT or Android Studio?

**Comment by MaiadaMahmoud** [comment]
I'm testing the TomDroid application, I got the source code online. It's attached here
[tomdroid-src-0.5.0.zip](https://github.com/reverse-unina/AndroidRipper/files/255003/tomdroid-src-0.5.0.zip)

**Comment by nicola-amatucci** [comment]
I've added the "project.properties" file to your project.

[tomdroid-src-0.5.0.zip](https://github.com/reverse-unina/AndroidRipper/files/255182/tomdroid-src-0.5.0.zip)
